APT::FTPArchive::Release {
  Origin "VAJ";
  Label "VAJ Terminal";
  Suite "stable";
  Codename "stable";
  Architectures "aarch64";
  Components "main";
  Description "VAJ Terminal Package Repository";
};

Dir {
  ArchiveDir ".";
  OverrideDir ".";
  CacheDir ".";
};

TreeDefault {
  Directory "pool/";
  SrcDirectory "pool/";
};

BinDirectory "dists/stable/main/binary-aarch64" {
  Packages "dists/stable/main/binary-aarch64/Packages";
};

Default {
  Packages {
    Extensions ".deb";
    Compress ". gzip";
  };
  Contents {
    Compress "gzip";
  };
};
