#!/usr/bin/env python3
"""publish-r2.py — Upload repository files to Cloudflare R2 via S3 API.

Reads AWS/R2 credentials from environment. Uses allowlist from foundation
manifest (manifests/foundation.tsv) to permit only certified files.

Usage:
    source ~/.config/vaj-apt/r2.env
    python3 scripts/publish-r2.py [file ...] | --all \
        | --verify \
        | --refresh-metadata-cache-policy [--dry-run]
"""

import argparse, gzip, hashlib, hmac, datetime, importlib.util, json, os, socket, sys, tempfile, urllib.request, urllib.error
from pathlib import Path
from urllib.parse import quote

# Cloudflare R2 S3 endpoints always publish A (IPv4) records. Some hosts
# (notably WSL2) have broken IPv6 egress to Cloudflare that does not fail fast
# but hangs each request until the socket timeout (~60s), then retries -- so a
# publish stalls for many minutes instead of erroring. Force IPv4 resolution
# unless a future IPv6-only host explicitly opts out with PUBLISH_R2_ALLOW_IPV6.
if not os.environ.get("PUBLISH_R2_ALLOW_IPV6"):
    _orig_getaddrinfo = socket.getaddrinfo

    def _ipv4_only_getaddrinfo(host, port, family=0, *args, **kwargs):
        return _orig_getaddrinfo(host, port, socket.AF_INET, *args, **kwargs)

    socket.getaddrinfo = _ipv4_only_getaddrinfo

MANIFEST_PATH = "manifests/foundation.tsv"
_GENERATOR_MODULE_PATH = os.path.join(os.path.dirname(__file__), "generate_repo.py")
_GENERATOR_SPEC = importlib.util.spec_from_file_location("vaj_generate_repo", _GENERATOR_MODULE_PATH)
gen = importlib.util.module_from_spec(_GENERATOR_SPEC)
sys.modules[_GENERATOR_SPEC.name] = gen
_GENERATOR_SPEC.loader.exec_module(gen)

SUITE = "stable"
COMPONENT = "main"
ARCHITECTURE = "binary-aarch64"
PROVENANCE_REL_PATH = f"dists/{SUITE}/{gen.PROVENANCE_FILENAME}"

MUTABLE_METADATA = frozenset([
    f"dists/{SUITE}/InRelease",
    f"dists/{SUITE}/Release",
    f"dists/{SUITE}/Release.gpg",
    f"dists/{SUITE}/{COMPONENT}/{ARCHITECTURE}/Packages",
    f"dists/{SUITE}/{COMPONENT}/{ARCHITECTURE}/Packages.gz",
])

MUTABLE_CACHE_CONTROL = "max-age=0, must-revalidate"


def load_allowlist(repo_root):
    """Load allowed object paths from the foundation manifest."""
    manifest = os.path.join(repo_root, MANIFEST_PATH)
    allowed = set()
    if os.path.exists(manifest):
        with open(manifest) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) >= 5:
                    allowed.add(parts[4])
    # Also allow metadata and key files
    allowed.add(f"dists/{SUITE}/Release")
    allowed.add(f"dists/{SUITE}/Release.gpg")
    allowed.add(f"dists/{SUITE}/InRelease")
    allowed.add(f"dists/{SUITE}/{COMPONENT}/{ARCHITECTURE}/Packages")
    allowed.add(f"dists/{SUITE}/{COMPONENT}/{ARCHITECTURE}/Packages.gz")
    allowed.add(PROVENANCE_REL_PATH)
    allowed.add("keys/io-vaj-archive.gpg")
    allowed.add("keys/io-vaj-archive.asc")
    return allowed


def _parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Publish VAJ APT repository content to Cloudflare R2.",
    )
    parser.add_argument(
        "files",
        nargs="*",
        help="relative repository paths to upload, or omit when using a mode flag",
    )
    parser.add_argument("--all", action="store_true", help="upload the manifest allowlist")
    parser.add_argument("--verify", action="store_true", help="verify mutable metadata cache policy")
    parser.add_argument(
        "--refresh-metadata-cache-policy",
        action="store_true",
        help="re-upload only mutable metadata with the canonical Cache-Control header",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print refresh-metadata actions without uploading",
    )
    parser.add_argument(
        "--validate-provenance",
        action="store_true",
        help="validate that local metadata was generated by the shared manifest-authoritative generator",
    )
    parser.add_argument(
        "--repo-root",
        help="override the repository root used for manifest and pool validation",
    )
    parser.add_argument(
        "--manifest",
        help="override the active manifest path used for provenance validation",
    )
    parser.add_argument(
        "--metadata-root",
        help="override the metadata tree root used for provenance validation",
    )
    args = parser.parse_args(argv)
    modes = sum(
        bool(flag)
        for flag in (
            args.all,
            args.verify,
            args.refresh_metadata_cache_policy,
            args.validate_provenance,
        )
    )
    if modes > 1:
        parser.error("choose only one mode flag from --all, --verify, --refresh-metadata-cache-policy, --validate-provenance")
    if args.dry_run and not args.refresh_metadata_cache_policy:
        parser.error("--dry-run is only valid with --refresh-metadata-cache-policy")
    if args.files and modes:
        parser.error("positional file uploads cannot be combined with a mode flag")
    if not args.files and not modes:
        parser.error("provide file paths or one mode flag")
    return args


def _require_r2_env():
    return (
        os.environ["R2_BUCKET"],
        os.environ["R2_S3_ENDPOINT"],
        os.environ["AWS_REGION"],
        os.environ["AWS_ACCESS_KEY_ID"],
        os.environ["AWS_SECRET_ACCESS_KEY"],
    )


def _sha256_file(path):
    return gen._hash_file(path, "sha256")


def _selected_package_tuples(entries):
    return [
        (entry.name, entry.version, entry.arch, entry.sha256, entry.object_path, entry.size)
        for entry in entries
    ]


def _selected_package_tuples_from_provenance(provenance):
    tuples = []
    for record in provenance.get("selected_packages", []):
        tuples.append(
            (
                record.get("name"),
                record.get("version"),
                record.get("arch"),
                record.get("sha256"),
                record.get("object_path"),
                record.get("size"),
            )
        )
    return tuples


def _provenance_path(metadata_root):
    return os.path.join(metadata_root, PROVENANCE_REL_PATH)


def _canonical_metadata_paths(metadata_root):
    return {
        "Packages": os.path.join(
            metadata_root,
            "dists",
            SUITE,
            COMPONENT,
            ARCHITECTURE,
            "Packages",
        ),
        "Packages.gz": os.path.join(
            metadata_root,
            "dists",
            SUITE,
            COMPONENT,
            ARCHITECTURE,
            "Packages.gz",
        ),
        "Release": os.path.join(metadata_root, "dists", SUITE, "Release"),
    }


def _read_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _validate_inrelease_matches_release(metadata_root):
    inrelease_path = os.path.join(metadata_root, "dists", SUITE, "InRelease")
    release_path = os.path.join(metadata_root, "dists", SUITE, "Release")
    if not os.path.isfile(inrelease_path):
        return
    if not os.path.isfile(release_path):
        raise RuntimeError("InRelease exists but Release is missing")
    with open(inrelease_path, "r", encoding="utf-8") as handle:
        inrelease_text = handle.read()
    start_marker = "\n\n"
    end_marker = "\n-----BEGIN PGP SIGNATURE-----\n"
    if not inrelease_text.startswith("-----BEGIN PGP SIGNED MESSAGE-----\n"):
        raise RuntimeError("InRelease is not a clearsigned Release file")
    if start_marker not in inrelease_text or end_marker not in inrelease_text:
        raise RuntimeError("InRelease is malformed and cannot be matched to Release")
    signed_body = inrelease_text.split(start_marker, 1)[1].split(end_marker, 1)[0]
    signed_body = signed_body.replace("\n- -", "\n-")
    with open(release_path, "r", encoding="utf-8") as handle:
        release_text = handle.read()
    if signed_body != release_text:
        raise RuntimeError("InRelease payload does not match Release")


def validate_metadata_provenance(repo_root, manifest_path, metadata_root):
    repo_root = Path(repo_root).resolve()
    manifest_path = Path(manifest_path).resolve()
    metadata_root = Path(metadata_root).resolve()
    manifest_entries = gen.load_manifest(manifest_path)
    provenance_path = metadata_root / PROVENANCE_REL_PATH
    if not provenance_path.is_file():
        raise RuntimeError(f"shared-generator provenance missing: {provenance_path}")

    provenance = _read_json(provenance_path)
    if provenance.get("schema_version") != gen.PROVENANCE_SCHEMA_VERSION:
        raise RuntimeError("provenance schema version mismatch")

    generator = provenance.get("generator", {})
    expected_generator = gen.generator_identity(repo_root)
    if generator != expected_generator:
        raise RuntimeError("provenance generator identity mismatch")

    manifest_record = provenance.get("manifest", {})
    manifest_rel = manifest_path.relative_to(repo_root).as_posix()
    if manifest_record.get("path") != manifest_rel:
        raise RuntimeError("provenance manifest path mismatch")
    if manifest_record.get("sha256") != gen.manifest_digest(manifest_path):
        raise RuntimeError("provenance manifest digest mismatch")
    if manifest_record.get("selected_package_count") != len(manifest_entries):
        raise RuntimeError("provenance package count mismatch")

    expected_packages = _selected_package_tuples(manifest_entries)
    actual_packages = _selected_package_tuples_from_provenance(provenance)
    if len(actual_packages) != len(set(actual_packages)):
        raise RuntimeError("provenance contains duplicate selected package records")
    if actual_packages != expected_packages:
        raise RuntimeError("provenance selected package set mismatch")

    release_generation = provenance.get("release_generation", {})
    if not release_generation.get("release_generated_by_shared_generator"):
        raise RuntimeError("provenance does not attest to shared-generator Release output")
    release_time_text = release_generation.get("release_time_utc")
    if not isinstance(release_time_text, str):
        raise RuntimeError("provenance release timestamp missing")
    release_time = gen._parse_release_time(release_time_text)

    artifact_paths = {
        name: Path(path)
        for name, path in _canonical_metadata_paths(metadata_root).items()
    }
    artifacts = provenance.get("artifacts", {})
    for artifact_name, artifact_path in artifact_paths.items():
        if not artifact_path.is_file():
            raise RuntimeError(f"canonical metadata missing: {artifact_name}")
        record = artifacts.get(artifact_name)
        if not isinstance(record, dict):
            raise RuntimeError(f"provenance missing artifact record for {artifact_name}")
        artifact_rel = artifact_path.relative_to(metadata_root).as_posix()
        if record.get("path") != artifact_rel:
            raise RuntimeError(f"provenance path mismatch for {artifact_name}")
        actual_size = artifact_path.stat().st_size
        if record.get("size") != actual_size:
            raise RuntimeError(f"provenance size mismatch for {artifact_name}")
        actual_sha = _sha256_file(artifact_path)
        if record.get("sha256") != actual_sha:
            raise RuntimeError(f"provenance digest mismatch for {artifact_name}")

    with tempfile.TemporaryDirectory(prefix="vaj-provenance-") as temp_root:
        regenerated = gen.generate_repository(
            manifest_path,
            repo_root,
            Path(temp_root),
            release_time=release_time,
        )
        for artifact_name, regen_path in (
            ("Packages", regenerated["packages_path"]),
            ("Packages.gz", regenerated["packages_gz_path"]),
            ("Release", regenerated["release_path"]),
            ("Provenance", regenerated["provenance_path"]),
        ):
            if artifact_name == "Provenance":
                current_path = provenance_path
            else:
                current_path = artifact_paths[artifact_name]
            with open(current_path, "rb") as current_handle, open(regen_path, "rb") as regen_handle:
                if current_handle.read() != regen_handle.read():
                    raise RuntimeError(f"{artifact_name} does not match shared-generator output")

    _validate_inrelease_matches_release(metadata_root)
    packages_stanzas = [
        stanza
        for stanza in artifact_paths["Packages"].read_text(encoding="utf-8").strip().split("\n\n")
        if stanza.strip()
    ]
    if len(packages_stanzas) != len(manifest_entries):
        raise RuntimeError("Packages stanza count mismatch")

    return {
        "manifest_sha256": manifest_record["sha256"],
        "package_count": len(manifest_entries),
        "provenance_path": provenance_path,
        "packages_path": artifact_paths["Packages"],
    }


def sign(key, msg):
    return hmac.new(key, msg.encode("utf-8"), hashlib.sha256).digest()


def get_signature_key(secret, date, region, service):
    kDate = sign(("AWS4" + secret).encode("utf-8"), date)
    kRegion = sign(kDate, region)
    kService = sign(kRegion, service)
    return sign(kService, "aws4_request")


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def s3_put(bucket, key, endpoint, region, access_key, secret_key, data, content_type, cache_control=None, _retries=4):
    import time
    for attempt in range(_retries + 1):
        status = _s3_put_once(bucket, key, endpoint, region, access_key, secret_key, data, content_type, cache_control)
        if status in (200, 201):
            return status
        if attempt < _retries:
            wait = 2 ** attempt
            print(f"  PUT {key}: got {status}, retrying in {wait}s (attempt {attempt+1}/{_retries})...", file=sys.stderr)
            time.sleep(wait)
    return status


def _s3_put_once(bucket, key, endpoint, region, access_key, secret_key, data, content_type, cache_control=None):
    service = "s3"
    encoded_bucket = quote(bucket, safe="")
    encoded_key = quote(key, safe="/~")
    url = f"{endpoint}/{encoded_bucket}/{encoded_key}"
    t = datetime.datetime.now(datetime.UTC)
    amzdate = t.strftime("%Y%m%dT%H%M%SZ")
    datestamp = t.strftime("%Y%m%d")
    payload_hash = sha256(data)
    host_part = endpoint.replace("https://", "")
    headers = {
        "Host": host_part,
        "X-Amz-Date": amzdate,
        "X-Amz-Content-SHA256": payload_hash,
        "Content-Type": content_type,
    }
    if cache_control is not None:
        headers["Cache-Control"] = cache_control
    signed_headers = ";".join(sorted(k.lower() for k in headers))
    canonical_headers = "".join(
        f"{k.lower()}:{v}\n"
        for k, v in sorted(headers.items(), key=lambda x: x[0].lower())
    )
    canonical_uri = f"/{encoded_bucket}/{encoded_key}"
    canonical_request = (
        f"PUT\n{canonical_uri}\n\n{canonical_headers}\n{signed_headers}\n{payload_hash}"
    )
    credential_scope = f"{datestamp}/{region}/{service}/aws4_request"
    string_to_sign = (
        f"AWS4-HMAC-SHA256\n{amzdate}\n{credential_scope}\n"
        + sha256(canonical_request.encode("utf-8"))
    )
    signing_key = get_signature_key(secret_key, datestamp, region, service)
    signature = hmac.new(
        signing_key, string_to_sign.encode("utf-8"), hashlib.sha256
    ).hexdigest()
    authorization = (
        f"AWS4-HMAC-SHA256 Credential={access_key}/{credential_scope}, "
        f"SignedHeaders={signed_headers}, Signature={signature}"
    )
    headers["Authorization"] = authorization
    req = urllib.request.Request(url, data=data, headers=headers, method="PUT")
    try:
        resp = urllib.request.urlopen(req, timeout=60)
        return resp.status
    except urllib.error.HTTPError as e:
        return e.code
    except urllib.error.URLError:
        return 0


def s3_head(bucket, key, endpoint, region, access_key, secret_key):
    """Send a HEAD request and return (status_code, response_headers_dict)."""
    service = "s3"
    encoded_bucket = quote(bucket, safe="")
    encoded_key = quote(key, safe="/~")
    url = f"{endpoint}/{encoded_bucket}/{encoded_key}"
    t = datetime.datetime.now(datetime.UTC)
    amzdate = t.strftime("%Y%m%dT%H%M%SZ")
    datestamp = t.strftime("%Y%m%d")
    host_part = endpoint.replace("https://", "")
    headers = {
        "Host": host_part,
        "X-Amz-Date": amzdate,
    }
    payload_hash = sha256(b"")
    headers["X-Amz-Content-SHA256"] = payload_hash
    signed_headers = ";".join(sorted(k.lower() for k in headers))
    canonical_headers = "".join(
        f"{k.lower()}:{v}\n"
        for k, v in sorted(headers.items(), key=lambda x: x[0].lower())
    )
    canonical_uri = f"/{encoded_bucket}/{encoded_key}"
    canonical_request = (
        f"HEAD\n{canonical_uri}\n\n{canonical_headers}\n{signed_headers}\n{payload_hash}"
    )
    credential_scope = f"{datestamp}/{region}/{service}/aws4_request"
    string_to_sign = (
        f"AWS4-HMAC-SHA256\n{amzdate}\n{credential_scope}\n"
        + sha256(canonical_request.encode("utf-8"))
    )
    signing_key = get_signature_key(secret_key, datestamp, region, service)
    signature = hmac.new(
        signing_key, string_to_sign.encode("utf-8"), hashlib.sha256
    ).hexdigest()
    authorization = (
        f"AWS4-HMAC-SHA256 Credential={access_key}/{credential_scope}, "
        f"SignedHeaders={signed_headers}, Signature={signature}"
    )
    headers["Authorization"] = authorization
    req = urllib.request.Request(url, method="HEAD", headers=headers)
    try:
        resp = urllib.request.urlopen(req, timeout=60)
        return resp.status, dict(resp.headers)
    except urllib.error.HTTPError as e:
        return e.code, dict(e.headers)


def s3_get(bucket, key, endpoint, region, access_key, secret_key):
    """Send a GET request and return (status_code, body_bytes, response_headers_dict)."""
    service = "s3"
    encoded_bucket = quote(bucket, safe="")
    encoded_key = quote(key, safe="/~")
    url = f"{endpoint}/{encoded_bucket}/{encoded_key}"
    t = datetime.datetime.now(datetime.UTC)
    amzdate = t.strftime("%Y%m%dT%H%M%SZ")
    datestamp = t.strftime("%Y%m%d")
    host_part = endpoint.replace("https://", "")
    headers = {
        "Host": host_part,
        "X-Amz-Date": amzdate,
    }
    payload_hash = sha256(b"")
    headers["X-Amz-Content-SHA256"] = payload_hash
    signed_headers = ";".join(sorted(k.lower() for k in headers))
    canonical_headers = "".join(
        f"{k.lower()}:{v}\n"
        for k, v in sorted(headers.items(), key=lambda x: x[0].lower())
    )
    canonical_uri = f"/{encoded_bucket}/{encoded_key}"
    canonical_request = (
        f"GET\n{canonical_uri}\n\n{canonical_headers}\n{signed_headers}\n{payload_hash}"
    )
    credential_scope = f"{datestamp}/{region}/{service}/aws4_request"
    string_to_sign = (
        f"AWS4-HMAC-SHA256\n{amzdate}\n{credential_scope}\n"
        + sha256(canonical_request.encode("utf-8"))
    )
    signing_key = get_signature_key(secret_key, datestamp, region, service)
    signature = hmac.new(
        signing_key, string_to_sign.encode("utf-8"), hashlib.sha256
    ).hexdigest()
    authorization = (
        f"AWS4-HMAC-SHA256 Credential={access_key}/{credential_scope}, "
        f"SignedHeaders={signed_headers}, Signature={signature}"
    )
    headers["Authorization"] = authorization
    req = urllib.request.Request(url, method="GET", headers=headers)
    try:
        resp = urllib.request.urlopen(req, timeout=60)
        return resp.status, resp.read(), dict(resp.headers)
    except urllib.error.HTTPError as e:
        body = b""
        try:
            body = e.read()
        except Exception:
            pass
        return e.code, body, dict(e.headers)


def _assert_metadata_key_eligible(key):
    """Refuse to operate on any path outside the five mutable metadata keys.
    Explicitly rejects /pool/ and any .deb.  Raises SystemExit on rejection."""
    if key.startswith("pool/") or "/pool/" in key:
        print(f"REFUSE  pool object: {key}", file=sys.stderr)
        sys.exit(2)
    if key.endswith(".deb"):
        print(f"REFUSE  .deb object: {key}", file=sys.stderr)
        sys.exit(2)
    if key not in MUTABLE_METADATA:
        print(f"REFUSE  not in MUTABLE_METADATA: {key}", file=sys.stderr)
        sys.exit(2)


def _refresh_metadata_cache_policy(repo_root, bucket, endpoint, region,
                                   access_key, secret_key, dry_run=False):
    """Re-upload the five canonical metadata objects with the required
    Cache-Control header, but only after verifying that the bytes already
    present on R2 equal the canonical local bytes.  This proves the operation
    mutates headers, not payload bytes, and never overwrites pool objects.

    On any pre-flight or post-upload error, the operation aborts without
    touching any further object.  This guarantees all-or-nothing semantics.

    Returns (verified_keys, errors).  Each entry is a dict with keys:
        path, local_sha256, origin_sha256, origin_bytes, status
    """
    results = []
    errors = []
    for key in sorted(MUTABLE_METADATA, key=_upload_order_key):
        local_path = os.path.join(repo_root, key)
        if not os.path.isfile(local_path):
            errors.append(f"{key}: canonical local file missing: {local_path}")
            return results, errors
        with open(local_path, "rb") as fh:
            local_data = fh.read()
        local_sha = sha256(local_data)
        if dry_run:
            print(f"DRY-RUN  {key}  local_sha256={local_sha}  bytes={len(local_data)}")
            results.append({
                "path": key,
                "local_sha256": local_sha,
                "origin_sha256": None,
                "origin_bytes": None,
                "status": "dry-run",
            })
            continue
        status, origin_data, _hdrs = s3_get(
            bucket, key, endpoint, region, access_key, secret_key,
        )
        if status != 200:
            errors.append(f"{key}: direct-R2 GET returned {status}")
            return results, errors
        origin_sha = sha256(origin_data)
        if origin_sha != local_sha:
            errors.append(
                f"{key}: origin/canonical byte mismatch "
                f"(origin={origin_sha}, local={local_sha}, "
                f"origin_bytes={len(origin_data)}, local_bytes={len(local_data)})"
            )
            return results, errors
        ct = content_type_for(key)
        put_status = s3_put(
            bucket, key, endpoint, region, access_key, secret_key,
            local_data, ct, cache_control=MUTABLE_CACHE_CONTROL,
        )
        if put_status not in (200, 201):
            errors.append(f"{key}: direct-R2 PUT returned {put_status}")
            return results, errors
        head_status, head_headers = s3_head(
            bucket, key, endpoint, region, access_key, secret_key,
        )
        if head_status != 200:
            errors.append(f"{key}: direct-R2 HEAD after upload returned {head_status}")
            return results, errors
        cc = head_headers.get("Cache-Control") or head_headers.get("cache-control", "")
        if cc != MUTABLE_CACHE_CONTROL:
            errors.append(
                f"{key}: post-upload Cache-Control mismatch: {cc!r} "
                f"(expected {MUTABLE_CACHE_CONTROL!r})"
            )
            return results, errors
        print(
            f"OK  {key}  bytes={len(local_data)}  sha256={local_sha}  "
            f"cache_control={cc!r}  head={head_status}"
        )
        results.append({
            "path": key,
            "local_sha256": local_sha,
            "origin_sha256": origin_sha,
            "origin_bytes": len(origin_data),
            "status": "uploaded",
        })
    return results, errors


def verify_cache_policy(bucket, endpoint, region, access_key, secret_key):
    """Post-upload HEAD check: ensure every mutable metadata object has the
    correct Cache-Control header. Returns list of error messages (empty=pass)."""
    errors = []
    for path in MUTABLE_METADATA:
        status, headers = s3_head(bucket, path, endpoint, region, access_key, secret_key)
        if status != 200:
            errors.append(f"{path}: HEAD returned {status}")
            continue
        cc = headers.get("Cache-Control") or headers.get("cache-control", "")
        if cc != MUTABLE_CACHE_CONTROL:
            errors.append(
                f"{path}: expected Cache-Control={MUTABLE_CACHE_CONTROL!r}, "
                f"got {cc!r}"
            )
    return errors


def content_type_for(path):
    if path.endswith(".deb"):
        return "application/vnd.debian.binary-package"
    elif path.endswith(".gpg"):
        return "application/pgp-keys"
    elif path.endswith(".asc"):
        return "text/plain"
    elif path.endswith(".gz"):
        return "application/gzip"
    elif path.endswith("Release") or path.endswith("InRelease") or path.endswith("Packages"):
        return "text/plain"
    return "application/octet-stream"


def _upload_order_key(path):
    """Sort key: pool objects first, then metadata in publication order."""
    metadata_order = [
        f"dists/{SUITE}/{COMPONENT}/{ARCHITECTURE}/Packages",
        f"dists/{SUITE}/{COMPONENT}/{ARCHITECTURE}/Packages.gz",
        f"dists/{SUITE}/Release",
        f"dists/{SUITE}/Release.gpg",
        f"dists/{SUITE}/InRelease",
    ]
    if path in metadata_order:
        return (1, metadata_order.index(path))
    return (0, path)


def main():
    args = _parse_args(sys.argv[1:])
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(args.repo_root or os.path.dirname(script_dir))
    manifest_path = os.path.abspath(args.manifest or os.path.join(repo_root, MANIFEST_PATH))
    metadata_root = os.path.abspath(args.metadata_root or repo_root)
    allowed = load_allowlist(repo_root)
    dry_run = args.dry_run

    if args.validate_provenance:
        result = validate_metadata_provenance(repo_root, manifest_path, metadata_root)
        print(
            f"OK  provenance validated for {result['package_count']} package stanzas "
            f"from active manifest {result['manifest_sha256']}"
        )
        return 0

    if args.refresh_metadata_cache_policy:
        _require_r2_env()
        validate_metadata_provenance(repo_root, manifest_path, metadata_root)
        bucket, endpoint, region, access_key, secret_key = _require_r2_env()
        if not dry_run:
            for k in MUTABLE_METADATA:
                _assert_metadata_key_eligible(k)
        _results, errors = _refresh_metadata_cache_policy(
            metadata_root, bucket, endpoint, region, access_key, secret_key,
            dry_run=dry_run,
        )
        if dry_run:
            print(
                f"DRY-RUN complete: {len(MUTABLE_METADATA)} mutable metadata keys "
                f"would be re-uploaded with Cache-Control: {MUTABLE_CACHE_CONTROL!r}"
            )
            return 0
        if errors:
            for e in errors:
                print(f"FAIL  {e}", file=sys.stderr)
            sys.exit(1)
        print(
            f"OK  refreshed Cache-Control on {len(MUTABLE_METADATA)} mutable metadata objects"
        )
        return 0

    if args.verify:
        bucket, endpoint, region, access_key, secret_key = _require_r2_env()
        errors = verify_cache_policy(bucket, endpoint, region, access_key, secret_key)
        if errors:
            for e in errors:
                print(f"FAIL  {e}", file=sys.stderr)
            sys.exit(1)
        print("OK  all mutable metadata Cache-Control is correct")
        return

    if args.all:
        bucket, endpoint, region, access_key, secret_key = _require_r2_env()
        validate_metadata_provenance(repo_root, manifest_path, metadata_root)
        files = sorted(allowed, key=_upload_order_key)
    else:
        bucket, endpoint, region, access_key, secret_key = _require_r2_env()
        validate_metadata_provenance(repo_root, manifest_path, metadata_root)
        files = args.files

    for rel_path in files:
        if rel_path in MUTABLE_METADATA or rel_path == PROVENANCE_REL_PATH:
            validate_metadata_provenance(repo_root, manifest_path, metadata_root)
            break

    for rel_path in files:
        local_path = os.path.join(metadata_root if rel_path.startswith("dists/") else repo_root, rel_path)
        if not os.path.isfile(local_path):
            print(f"SKIP (not found): {rel_path}", file=sys.stderr)
            continue
        if rel_path not in allowed:
            print(f"SKIP (not in allowlist): {rel_path}", file=sys.stderr)
            continue

        with open(local_path, "rb") as fh:
            data = fh.read()
        ct = content_type_for(rel_path)
        cc = MUTABLE_CACHE_CONTROL if rel_path in MUTABLE_METADATA else None
        status = s3_put(bucket, rel_path, endpoint, region, access_key, secret_key, data, ct, cache_control=cc)
        file_hash = sha256(data)
        print(f"PUT {status}  {rel_path}  sha256={file_hash}")


if __name__ == "__main__":
    main()
